---
title: "Covid-19 and Election Data"
output: flexdashboard::flex_dashboard
---
Dashboard {data-orientation=rows}
=====================================   

```{r setup, include = FALSE}
library(tidyverse)
library(lubridate)
library(datasets)
library(tidycensus)
library(dygraphs)
library(xts)

#Initial reading of the main data file
covid_counties <- read_csv("data_raw/us-counties.csv")
election_counties <- read_csv("data_raw/presidential_election_counties.csv")
masks_counties <- read_csv("data_raw/mask-use-by-county.csv")
# This is from :
#https://github.com/balsama/us_counties_data/blob/main/data/counties.csv#L15
population_counties <- get_estimates( geography = "county", year = "2019", variables = "POP")

#New York population data was incorrect from above source
#State population data pulled from census API
#install census api key for future session use
#census_api_key(key = "9de2c06af35b38352b1a400e0d2b53ecf2488a3f", install = TRUE)
#run this to load census api key and allow queries of census data
readRenviron("~/.Renviron")

#getting state population for 2019
state_population <- get_estimates( geography = "state", year = "2019", variables = "POP")

#data from fips_code and joining it to population_counties 
fips_codes <- tibble(fips_codes)

#data from satasets package to add 2 letter state abbr. column
states = tibble(state_abb = state.abb, state = str_to_lower(state.name)) %>%
  mutate(state_abb = factor(state_abb))


#-------------------------------------------------------------------------------

#creating 5 digit fips code and join to population_counties 
#16 counties in fips_code and not in population_counties
fips_codes_clean <- fips_codes %>%
  rename_all(str_to_lower) %>% 
  select(state_name, county, state_code, county_code) %>% 
  mutate(fips = paste0(state_code, county_code), 
         county =str_to_lower(county), 
         state_name  = str_to_lower(state_name),
         state = state_name) %>% 
  select(fips, state, county)

#rename specific values
fips_codes_clean[fips_codes_clean == "petersburg census area"] <- "petersburg borough"

fips_codes_clean[fips_codes_clean == "la salle parish"] <- "lasalle parish"


#Cleaning up county population data
#Join for final population_counties_clean

population_counties_clean <- population_counties %>% 
  separate(NAME, c("county", "state"), sep = ", ") %>% 
  rename_all(str_to_lower) %>% 
  select(-geoid, -variable) %>% 
  mutate(county = str_to_lower(county),
         state = str_to_lower(state),
         population = value) 

#cleaning accents
population_counties_clean[population_counties_clean == "doña ana county"] <- "dona ana county"

population_counties_clean <- population_counties_clean %>% 
  left_join(fips_codes_clean, by = c ("county", "state")) %>% 
  select (-value, -county, -state)

#Selecting only Trump & Biden results (along with other county identifying columns)
#Also creating percent_biden column that can be used for gradient stuff
election_counties_clean <- election_counties %>% 
  select(fips, name, state, results_trumpd, results_absentee_trumpd,
         results_bidenj, results_absentee_bidenj) %>% 
  mutate(name = str_to_lower(name),
         trump_total = results_trumpd + results_absentee_trumpd,
         biden_total = results_bidenj + results_absentee_bidenj,
         percent_biden = biden_total / (biden_total + trump_total),
         winner = if_else(biden_total > trump_total, "biden", "trump"),
         winner = factor(winner),
         state = str_replace(state, "-", " ")) %>% 
  rename(county = name) %>%
  filter(state != "district of-columbia")


### Retaining date column and changing date column to Date class
covid_counties_clean <- covid_counties %>% 
  filter(date == "2020-11-17") %>% 
  select(fips, county, state, cases, deaths) %>% 
  mutate(county = str_to_lower(county),
         state = str_to_lower(state))

covid_counties_clean_dates <- covid_counties %>% 
  mutate(date = ymd(date),
         county = str_to_lower(county),
         state = str_to_lower(state))


# CHECKING TO MAKE SURE CUMULATIVE AND NOT ACTIVE CASES
# covid_counties %>% 
#   filter(fips == "04013") %>% 
#   ggplot(aes(date, cases)) +
#   geom_lin

# each participant was asked: How often do you wear a mask in public when you expect to be within six feet of another person?
# 250,000 survey responses between July 2 and July 14
# mask_percent is just what I thought would give the % of people who "commonly" wear a mask in the county when in public
masks_counties_clean <- masks_counties %>% 
  rename_all(str_to_lower) %>% 
  rename(fips = countyfp) %>% 
  mutate(mask_percent = frequently + always)

#Combining Data Sets (ALASKA does not have accurate county population information)
#We have 40 counties in Alaska with election data, but no county population data 
master_covid_election <- covid_counties_clean %>% 
  inner_join(population_counties_clean, by = "fips") %>% 
  left_join(election_counties_clean, by = c("fips", "county", "state")) %>% 
  inner_join(masks_counties_clean, by = "fips") %>%
  inner_join(states, by = "state")

master_covid_election_with_dates <- covid_counties_clean_dates %>% 
  inner_join(population_counties_clean, c("fips")) %>% 
  left_join(election_counties_clean, by = c("fips", "county", "state")) %>% 
  inner_join(masks_counties_clean, by = "fips") %>%
  inner_join(states, by = "state")

sum(is.na(master_covid_election_with_dates$fips))

# #Just looking at what counties had the highest death rate
# master_covid_election %>% 
#   mutate(death_rate = (deaths / population) * 100) %>% 
#   select(state, county, death_rate) %>% 
#   arrange(desc(death_rate))


#states won biden or trump. source = https://www.270towin.com/2020-election-results-live/
biden_states <- c("WA", "OR", "CA", "NV", "AZ", "NM", "CO", "HI", "MN", "WI", 
                  "IL", "MI", "GA", "PA", "VA", "NY", "VT", "NH", "MA", "RI", 
                  "CT", "NJ", "DE", "MD", "DC")
trump_states <- c("AK", "ID", "UT", "MT", "WY", "ND", "SD", "KS", "OK", "TX", 
                  "LA", "IA", "MO", "AR", "MS", "AL", "TN", "KY", "IN", "OH", 
                  "WV", "NC", "SC", "FL")
split_states <- c("NE", "ME")

#adding state win column
master_covid_election <- master_covid_election %>%
  mutate(state_win = case_when(state_abb %in% biden_states ~ "biden",
                               state_abb %in% trump_states ~ "trump",
                               state_abb %in% split_states ~ "split",
                               is.na(winner) & state %in% biden_states ~ "biden",
                               is.na(winner)& state %in% trump_states ~ "trump",
                               is.na(winner)& state %in% split_states ~ "split"))

master_covid_election_with_dates <- master_covid_election_with_dates %>%
  mutate(state_win = case_when(state_abb %in% biden_states ~ "biden",
                               state_abb %in% trump_states ~ "trump",
                               state_abb %in% split_states ~ "split",
                               is.na(winner) & state %in% biden_states ~ "biden",
                               is.na(winner)& state %in% trump_states ~ "trump",
                               is.na(winner)& state %in% split_states ~ "split"))

#adding total cases per state column
total_state_cases <- master_covid_election %>%
  group_by(state_abb) %>%
  summarise(total_cases = sum(cases))

master_covid_election <- master_covid_election %>%
  inner_join(total_state_cases, by = "state_abb") %>%
  mutate(state = factor(state),
         state_abb = factor(state_abb))

total_state_cases <- master_covid_election_with_dates %>%
  group_by(state_abb, date) %>%
  summarise(total_cases = sum(cases))

master_covid_election_with_dates <- master_covid_election_with_dates %>%
  inner_join(total_state_cases, by = c("state_abb", "date")) %>%
  mutate(state = factor(state),
         state_abb = factor(state_abb))

# replacing NAs in winner column with info from state_win
master_covid_election <- master_covid_election %>%
  mutate(winner = case_when(is.na(winner) ~ state_win,
                            !is.na(winner) ~ as.character(winner)),
         death_rate_per_100k = (deaths / population) * 100000,
         infection_rate_per_100k = (cases / population) * 100000,
         death_rate = (deaths / population),
         infection_rate = (cases / population))

master_covid_election_with_dates <- master_covid_election_with_dates %>%
  mutate(winner = case_when(is.na(winner) ~ state_win,
                            !is.na(winner) ~ as.character(winner)),
         death_rate_per_100k = (deaths / population) * 100000,
         infection_rate_per_100k = (cases / population) * 100000,
         death_rate = (deaths / population),
         infection_rate = (cases / population))



master_covid_election_with_dates <- master_covid_election_with_dates %>%
  mutate(winner = case_when(is.na(winner) ~ state_win,
                            !is.na(winner) ~ as.character(winner)))

#replacing NAs in other columns with 0's
master_covid_election[is.na(master_covid_election)] <- 0
master_covid_election_with_dates[is.na(master_covid_election_with_dates)] <- 0

#adding state population to covid_master
state_population <- state_population %>%
  rename(state = NAME,
         state_population = value) %>%
  mutate(state = str_to_lower(state)) %>%
  select(-GEOID, -variable)

master_covid_election_with_dates <- master_covid_election_with_dates %>%
  left_join(state_population, by = "state") %>%
  mutate(state_abb = factor(state_abb),
         cases_biden = cases * percent_biden, #adds cases by proportion biden col
         cases_trump = cases * (1 - percent_biden)) #adds cases by proportion trump col

master_covid_election <- master_covid_election %>%
  left_join(state_population, by = "state") %>%
  mutate(state_abb = factor(state_abb),
         cases_biden = cases * percent_biden, #adds cases by proportion biden col
         cases_trump = cases * (1 - percent_biden)) #adds cases by proportion trump col

####data specific to Chart 2 ####

#Add county,ST label column for top infected county line labels
master_covid_election_with_dates <- master_covid_election_with_dates %>%
  mutate(county_st = paste(str_to_title(county), state_abb, sep = ", "))

#counties with highest infection rate
plot_data_topcounties_infect <- master_covid_election_with_dates %>%
  select(date, winner, infection_rate_per_100k, death_rate_per_100k, county_st) %>%
  group_by(winner, county_st) %>%
  summarize(mean_infect_100k = mean(infection_rate_per_100k),
            mean_death_100k = mean(death_rate_per_100k)) %>%
  slice_max(n = 3, order_by = mean_infect_100k)

biden_highest_infect <- plot_data_topcounties_infect %>% filter(winner == "biden") %>% pull(county_st)
trump_highest_infect <- plot_data_topcounties_infect %>% filter(winner == "trump") %>% pull(county_st)

#counties with highest death rate
plot_data_topcounties_death <- master_covid_election_with_dates %>%
  select(date, winner, infection_rate_per_100k, death_rate_per_100k, county_st) %>%
  group_by(winner, county_st) %>%
  summarize(mean_infect_100k = mean(infection_rate_per_100k),
            mean_death_100k = mean(death_rate_per_100k)) %>%
  slice_max(n = 3, order_by = mean_death_100k)

biden_highest_death <- plot_data_topcounties_death %>% filter(winner == "biden") %>% pull(county_st)
trump_highest_death <- plot_data_topcounties_death %>% filter(winner == "trump") %>% pull(county_st)


make_top_counties_df <- function(county_st_vect, df, candidate, i_or_d) {
  #county_st_vect = character vector of "County, ST" strings of counties
  #df = dataframe with column containing strings that match to those in county_st
  #candidate = "biden" or "trump"
  #i_or_d = "infect" or "death"
  #outputs lsit of dataframes filtered only to a single element in county_st_vect named data_list
  dfs_list <- list()
  names <- c()
  for (i in 1:length(county_st_vect)){
    dfs_list[[i]] <- df[df$county_st == county_st_vect[i], ]
    names <- c(names, str_replace(paste("df", 
                                county_st_vect[i], 
                                sep = "_"), pattern = ", ", "_"))
  }
  names <- str_replace_all(names, " ", "_")
  df_names <- c()
  for (j in names){
    df_names <- c(df_names, paste(j,candidate, i_or_d, sep = "_"))
  }
  names(dfs_list) <- df_names
  dfs_list <- map(dfs_list, ~select(.x, date, infection_rate_per_100k, death_rate_per_100k))
  list2env(dfs_list, envir = .GlobalEnv)
 }

#creating dataframes for individual counties with highest infection and death rates that went trump or biden
make_top_counties_df(biden_highest_death, master_covid_election_with_dates, "biden", "death")
make_top_counties_df(trump_highest_death, master_covid_election_with_dates, "trump", "death")
make_top_counties_df(biden_highest_infect, master_covid_election_with_dates, "biden", "infect")
make_top_counties_df(trump_highest_infect, master_covid_election_with_dates, "trump", "infect")

#making character vector of dataframe names
dfs_char_vect <- ls() %>%
  str_subset(pattern = "^df_")

#renaming dataframe columns to contain county name and trump or biden information
for (i in 1:length(dfs_char_vect)){
  x <- get(dfs_char_vect[i])
  if (str_detect(dfs_char_vect[i], "biden") & str_detect(dfs_char_vect[i], "infect")){
    new_cols <- c("date", paste("infect_100k_biden", dfs_char_vect[i], sep = "_"), paste("death_100k_biden", dfs_char_vect[i], sep = "_"))
    colnames(x) <- new_cols
    assign(dfs_char_vect[i],x)
  }
  else if (str_detect(dfs_char_vect[i], "biden") & str_detect(dfs_char_vect[i], "death")){
    new_cols <- c("date", paste("infect_100k_biden", dfs_char_vect[i], sep = "_"), paste("death_100k_biden", dfs_char_vect[i], sep = "_"))
    colnames(x) <- new_cols
    assign(dfs_char_vect[i],x)
  }
  else if (str_detect(dfs_char_vect[i], "trump") & str_detect(dfs_char_vect[i], "death")){
    new_cols <- c("date", paste("infect_100k_trump", dfs_char_vect[i], sep = "_"), paste("death_100k_trump", dfs_char_vect[i], sep = "_"))
    colnames(x) <- new_cols
    assign(dfs_char_vect[i],x)
  } 
  else if (str_detect(dfs_char_vect[i], "trump") & str_detect(dfs_char_vect[i], "infect")){
    new_cols <- c("date", paste("infect_100k_trump", dfs_char_vect[i], sep = "_"), paste("death_100k_trump", dfs_char_vect[i], sep = "_"))
    colnames(x) <- new_cols
    assign(dfs_char_vect[i],x)
  }
}

#combining all the dataframes together by date
top_infect_death <- get(dfs_char_vect[1])
for (i in 2:length(dfs_char_vect)){
  x <- get(dfs_char_vect[i])
  top_infect_death <- full_join(top_infect_death, x, by = "date")
}

#remove columns that don't have either "infect" or "death" twice
keep <- c()
for (i in colnames(top_infect_death)){
  if (str_detect(i, "^death.*death$") | str_detect(i, "^infect.*infect$") | i == "date"){
    keep <- c(keep, TRUE)
  }
  else {
    keep <- c(keep, FALSE)
  }
}

top_infect_death <- top_infect_death[,keep]

#averaging infection rate per 100k and death rate per 100k for biden and trump counties
plot_data <- master_covid_election_with_dates %>%
  select(date, winner, infection_rate_per_100k, death_rate_per_100k) %>%
  group_by(date, winner) %>%
  summarize(mean_infect_100k = mean(infection_rate_per_100k),
            mean_death_100k = mean(death_rate_per_100k)) 

#separating only to trump counties
plot_data_trump <- plot_data %>%
  filter(winner == "trump") %>%
  rename(mean_infect_100k_trump = mean_infect_100k,
         mean_death_100k_trump = mean_death_100k) %>%
  select(-winner) 

#separating only to biden counties
plot_data_biden <- plot_data %>%
  filter(winner == "biden") %>%
  rename(mean_infect_100k_biden = mean_infect_100k,
         mean_death_100k_biden = mean_death_100k) %>%
  select(-winner) 

#joining data
plot_data <- plot_data_biden %>%
  full_join(plot_data_trump, by = "date") %>%
  full_join(top_infect_death, by = "date")
  
#setting NA values to 0
plot_data[is.na(plot_data)] <- 0

#creating data for infection rate plot and death rate plot
plot_data_infect <- plot_data %>%
  select(date, contains("infect")) 

plot_data_death <- plot_data %>%
  select(date, contains("death")) 

#converting to timeseries objects
plot_data_infect <- xts(plot_data_infect[,-1], order.by = plot_data_infect$date)
plot_data_death <- xts(plot_data_death[,-1], order.by = plot_data_death$date)
```



   
Row {data-height=600}
-------------------------------------

### Chart 1

```{r}
```

Row {data-height=400}
-------------------------------------
   
### Chart 2

```{r}
#generating infection dygraph
dy_infect <- dygraph(data = plot_data_infect,
        main = "County Infection Rate by 2020 Presidential Election Winner",
        ylab = "Infection Rate / 100k People") %>%
  dySeries("mean_infect_100k_biden", 
           label = "Biden Counties Avg.",
           fillGraph = TRUE,
           color = "blue") %>%
  dySeries("infect_100k_biden_df_Buffalo_SD_biden_infect", 
           label = "Buffalo, SD",
           color = "blue") %>%
  dySeries("infect_100k_biden_df_Issaquena_MS_biden_infect", 
           label = "Issaquena, MS",
           color = "blue") %>%
  dySeries("infect_100k_biden_df_Lee_AR_biden_infect", 
           label = "Lee, AR",
           color = "blue") %>%
  dySeries("mean_infect_100k_trump", 
           label = "Trump Counties Avg.",
           fillGraph = TRUE,
           color = "red") %>%
  dySeries("infect_100k_trump_df_Lake_TN_trump_infect", 
           label = "Lake, TN",
           color = "red") %>%
  dySeries("infect_100k_trump_df_Lincoln_AR_trump_infect", 
           label = "Lincoln, AR",
           color = "red") %>%
  dySeries("infect_100k_trump_df_Trousdale_TN_trump_infect", 
           label = "Trousdale, TN",
           color = "red") %>%
  dyRangeSelector(height = 20) %>%
  dyLegend(show = "follow", width = 400) 


#generating death dygraph
dy_death <- dygraph(data = plot_data_death,
        main = "County Death Rate by 2020 Presidential Election Winner",
        ylab = "Death Rate / 100k People") %>%
  dySeries("mean_death_100k_biden", 
           label = "Biden Counties Avg.",
           fillGraph = TRUE,
           color = "blue") %>%
  dySeries("death_100k_biden_df_Randolph_GA_biden_death", 
           label = "Randolph, GA",
           color = "blue") %>%
  dySeries("death_100k_biden_df_Hancock_GA_biden_death", 
           label = "Hancock, GA",
           color = "blue") %>%
  dySeries("death_100k_biden_df_Terrell_GA_biden_death", 
           label = "Terrell, GA",
           color = "blue") %>%
  dySeries("mean_death_100k_trump", 
           label = "Trump Counties Avg.",
           fillGraph = TRUE,
           color = "red") %>%
  dySeries("death_100k_trump_df_Early_GA_trump_death", 
           label = "Early, GA",
           color = "red") %>%
  dySeries("death_100k_trump_df_Kenedy_TX_trump_death", 
           label = "Kenedy, TX",
           color = "red") %>%
  dySeries("death_100k_trump_df_Perkins_NE_trump_death", 
           label = "Perkins, NE",
           color = "red") %>%
  dyRangeSelector(height = 20) %>%
  dyLegend(show = "follow", width = 400) 

dy_infect
```   
    
### Chart 3

```{r}
```

Dashboard Descriptions
=====================================  
    
-------------------------------------
    
### Chart 1
    
Some comment 
   
### Chart 2

some comment

### Chart 3
    
Some comment

