---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
source("data_cleaning.R")

master_covid_election_with_dates$state <- str_to_title(master_covid_election_with_dates$state)
state_names <- sort(unique(master_covid_election_with_dates$state))

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('state_name', label = 'State', choices = state_names, selected = "Colorado")
 
```

Column
-----------------------------------------------------------------------

### Covid cases by state

```{r}

selectedData <- reactive({
  master_covid_election_with_dates[input$state_name]
})

clusters <- reactive({
  kmeans(selectedData(), input$clusters)
})

renderPlot({
  par(mar = c(5.1, 4.1, 0, 1))
  plot(selectedData(),
       col = clusters()$cluster,
       pch = 20, cex = 3)
  points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
})
```
